-- MySQL Script generated by MySQL Workbench
-- Fri Apr 30 15:41:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema universidade_u
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidade_u
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidade_u` DEFAULT CHARACTER SET utf8 ;
USE `universidade_u` ;

-- -----------------------------------------------------
-- Table `universidade_u`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `idade` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `data_inscricao_curso` DATE NOT NULL,
  `valor_pago_curso` FLOAT(10,2) NOT NULL,
  `ativo_sn` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `uc_aluno_cpf` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `uc_aluno_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universidade_u`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universidade_u`.`aluno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`aluno_curso` (
  `id_aluno_curso` INT NOT NULL AUTO_INCREMENT,
  `fk_id_aluno` INT NULL DEFAULT NULL,
  `fk_id_curso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_aluno_curso`),
  INDEX `fk_aluno_curso` (`fk_id_aluno` ASC) VISIBLE,
  INDEX `fk_curso_aluno` (`fk_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_curso`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `universidade_u`.`aluno` (`id_aluno`),
  CONSTRAINT `fk_curso_aluno`
    FOREIGN KEY (`fk_id_curso`)
    REFERENCES `universidade_u`.`curso` (`id_curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universidade_u`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `fk_id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  UNIQUE INDEX `uc_endereco_fk_id_aluno` (`fk_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_enredeco`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `universidade_u`.`aluno` (`id_aluno`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universidade_u`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `fk_id_aluno` INT NOT NULL,
  `tipo` ENUM('res', 'com', 'cel') NOT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_aluno_telefone` (`fk_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_telefone`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `universidade_u`.`aluno` (`id_aluno`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
