-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 12:10:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema universidade_u
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidade_u
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidade_u` DEFAULT CHARACTER SET utf8 ;
USE `universidade_u` ;

-- -----------------------------------------------------
-- Table `universidade_u`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NULL,
  `sexo` CHAR(1) NULL,
  `idade` INT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(150) NULL,
  `telefone` VARCHAR(20) NULL,
  `data_inscricao_curso` DATE NULL,
  `valor_pago_curso` FLOAT(10,2) NULL,
  `ativo_sn` INT NULL,
  `endereco` TEXT NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` CHAR(2) NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
