-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 19:23:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema universidade_u
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidade_u
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidade_u` DEFAULT CHARACTER SET utf8 ;
USE `universidade_u` ;

-- -----------------------------------------------------
-- Table `universidade_u`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `idade` INT NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `data_inscricao_curso` DATE NULL DEFAULT NULL,
  `valor_pago_curso` FLOAT(10,2) NULL DEFAULT NULL,
  `ativo_sn` INT NULL DEFAULT NULL,
  `endereco` TEXT NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universidade_u`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidade_u`.`telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `tipo` CHAR(3) NULL DEFAULT NULL,
  `fk_id_aluno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_aluno_telefone` (`fk_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_telefone`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `universidade_u`.`aluno` (`id_aluno`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
